import type { IRating } from "./types";

export const RATINGS: IRating[] = [
  {
    id: 1,
    accountId: 1,
    listingMapId: 155613,
    reservationId: 1,
    autoReviewId: null,
    timeDelta: null,
    scheduledDateTime: null,
    channelId: 2005,
    type: "guest-to-host",
    status: "awaiting",
    rating: null,
    externalReviewId: null,
    externalReservationId: null,
    publicReview: null,
    privateFeedback: null,
    revieweeResponse: null,
    isRevieweeRecommended: null,
    isCancelled: 0,
    autoReviewTemplateId: null,
    reviewCategory: [],
    departureDate: "2021-05-11 22:00:00",
    arrivalDate: "2021-05-06 08:00:00",
    listingName: "Beautiful and cozy apartment close to city center",
    guestName: "Andrew Peterson",
  },
  {
    id: 2,
    accountId: 2,
    listingMapId: 155615,
    reservationId: 2,
    autoReviewId: null,
    timeDelta: null,
    scheduledDateTime: null,
    channelId: 2005,
    type: "host-to-guest",
    status: "completed",
    rating: 5,
    externalReviewId: "REV-2024-001",
    externalReservationId: "RES-2024-001",
    publicReview:
      "Excellent guest! Very respectful and kept the apartment clean.",
    privateFeedback: "Would definitely host again.",
    revieweeResponse: "Thank you for the wonderful stay!",
    isRevieweeRecommended: 1,
    isCancelled: 0,
    autoReviewTemplateId: null,
    reviewCategory: [
      {
        category: "cleanliness",
        rating: 10,
      },
      {
        category: "communication",
        rating: 10,
      },
      {
        category: "respect_house_rules",
        rating: 10,
      },
    ],
    departureDate: "2024-01-15 11:00:00",
    arrivalDate: "2024-01-10 15:00:00",
    listingName: "Modern loft in downtown district",
    guestName: "Sarah Johnson",
  },
  {
    id: 3,
    accountId: 3,
    listingMapId: 346994,
    reservationId: 3,
    autoReviewId: 123,
    timeDelta: 48,
    scheduledDateTime: "2024-02-20 10:00:00",
    channelId: 2006,
    type: "guest-to-host",
    status: "pending",
    rating: 4,
    externalReviewId: "REV-2024-002",
    externalReservationId: "RES-2024-002",
    publicReview:
      "Great location and clean apartment. Host was very responsive.",
    privateFeedback: "Minor issue with hot water, but overall good experience.",
    revieweeResponse: null,
    isRevieweeRecommended: 1,
    isCancelled: 0,
    autoReviewTemplateId: 456,
    reviewCategory: [
      {
        category: "cleanliness",
        rating: 8,
      },
      {
        category: "communication",
        rating: 9,
      },
      {
        category: "check_in",
        rating: 8,
      },
      {
        category: "accuracy",
        rating: 7,
      },
    ],
    departureDate: "2024-02-18 12:00:00",
    arrivalDate: "2024-02-12 14:00:00",
    listingName: "Charming studio with garden view",
    guestName: "Michael Chen",
  },
  {
    id: 4,
    accountId: 4,
    listingMapId: 234567,
    reservationId: 4,
    autoReviewId: 124,
    timeDelta: 36,
    scheduledDateTime: "2024-03-10 09:00:00",
    channelId: 2005,
    type: "host-to-guest",
    status: "completed",
    rating: 3,
    externalReviewId: "REV-2024-003",
    externalReservationId: "RES-2024-003",
    publicReview: "Good stay overall. Some room for improvement.",
    privateFeedback: "Guest was okay, but communication could be better.",
    revieweeResponse: "Thanks for your feedback!",
    isRevieweeRecommended: 0,
    isCancelled: 0,
    autoReviewTemplateId: 457,
    reviewCategory: [
      {
        category: "cleanliness",
        rating: 6,
      },
      {
        category: "communication",
        rating: 5,
      },
      {
        category: "respect_house_rules",
        rating: 7,
      },
    ],
    departureDate: "2024-03-08 11:00:00",
    arrivalDate: "2024-03-05 16:00:00",
    listingName: "Spacious penthouse with city skyline",
    guestName: "Emily Rodriguez",
  },
  {
    id: 5,
    accountId: 5,
    listingMapId: 789012,
    reservationId: 5,
    autoReviewId: null,
    timeDelta: null,
    scheduledDateTime: null,
    channelId: 2006,
    type: "guest-to-host",
    status: "scheduled",
    rating: null,
    externalReviewId: null,
    externalReservationId: null,
    publicReview: null,
    privateFeedback: null,
    revieweeResponse: null,
    isRevieweeRecommended: null,
    isCancelled: 0,
    autoReviewTemplateId: null,
    reviewCategory: [],
    departureDate: "2024-04-05 10:00:00",
    arrivalDate: "2024-04-01 14:00:00",
    listingName: "Cozy cottage by the lake",
    guestName: "David Williams",
  },
  {
    id: 6,
    accountId: 6,
    listingMapId: 345678,
    reservationId: 6,
    autoReviewId: 125,
    timeDelta: 24,
    scheduledDateTime: "2024-05-15 14:00:00",
    channelId: 2005,
    type: "host-to-guest",
    status: "submitted",
    rating: 4,
    externalReviewId: "REV-2024-004",
    externalReservationId: "RES-2024-004",
    publicReview: "Nice guest, would recommend.",
    privateFeedback: "Friendly and respectful.",
    revieweeResponse: null,
    isRevieweeRecommended: 1,
    isCancelled: 0,
    autoReviewTemplateId: 458,
    reviewCategory: [
      {
        category: "cleanliness",
        rating: 9,
      },
      {
        category: "communication",
        rating: 8,
      },
    ],
    departureDate: "2024-05-12 10:00:00",
    arrivalDate: "2024-05-08 15:00:00",
    listingName: "Urban apartment with terrace",
    guestName: "Lisa Martinez",
  },
  {
    id: 7,
    accountId: 7,
    listingMapId: 456789,
    reservationId: 7,
    autoReviewId: 126,
    timeDelta: 72,
    scheduledDateTime: "2024-06-20 09:00:00",
    channelId: 2006,
    type: "guest-to-host",
    status: "published",
    rating: 5,
    externalReviewId: "REV-2024-005",
    externalReservationId: "RES-2024-005",
    publicReview: "Outstanding property! Highly recommend to everyone.",
    privateFeedback: "Perfect experience from start to finish.",
    revieweeResponse: "Thank you so much for your kind words!",
    isRevieweeRecommended: 1,
    isCancelled: 0,
    autoReviewTemplateId: 459,
    reviewCategory: [
      {
        category: "cleanliness",
        rating: 10,
      },
      {
        category: "communication",
        rating: 10,
      },
      {
        category: "accuracy",
        rating: 10,
      },
      {
        category: "location",
        rating: 10,
      },
    ],
    departureDate: "2024-06-18 11:00:00",
    arrivalDate: "2024-06-12 16:00:00",
    listingName: "Luxury villa with pool",
    guestName: "Robert Anderson",
  },
  {
    id: 8,
    accountId: 8,
    listingMapId: 567890,
    reservationId: 8,
    autoReviewId: 127,
    timeDelta: null,
    scheduledDateTime: null,
    channelId: 2005,
    type: "host-to-guest",
    status: "expired",
    rating: null,
    externalReviewId: null,
    externalReservationId: "RES-2024-006",
    publicReview: null,
    privateFeedback: null,
    revieweeResponse: null,
    isRevieweeRecommended: null,
    isCancelled: 0,
    autoReviewTemplateId: 460,
    reviewCategory: [],
    departureDate: "2023-12-20 10:00:00",
    arrivalDate: "2023-12-15 14:00:00",
    listingName: "Mountain cabin retreat",
    guestName: "Jennifer Taylor",
  },
];
