import type { IListing } from "./types";

export const MOCK_LISTINGS: IListing[] = [
  {
    id: 40160,
    propertyTypeId: 1,
    name: "Beautiful and cozy apartment close to city center",
    externalListingName: "Beautiful and cozy apartment close to city center",
    internalListingName: "Property #1",
    description:
      "In a classic Bremerhaven house we rent out our apartment which has a living room, bed room and is close to all the restaurants and nightlife.",
    houseRules: "No smoking, no parties",
    keyPickup: "Self check-in with lockbox",
    specialInstruction: "Please remove shoes at entrance",
    doorSecurityCode: "ddff8",
    country: "Germany",
    countryCode: "DE",
    state: "Bremen",
    city: "Bremerhaven",
    street: "Schulstraße 7",
    address: "Schulstraße 7, Bremerhaven, Bremen 27570, Germany",
    publicAddress: "Bremerhaven, Bremen 27570, Germany",
    zipcode: "27570",
    price: 211.62,
    starRating: 2.5,
    averageReviewRating: 9.2,
    weeklyDiscount: 0.71,
    monthlyDiscount: 0.82,
    propertyRentTax: 12,
    guestPerPersonPerNightTax: 10,
    guestStayTax: 12,
    guestNightlyTax: 13,
    guestBathroomsNumber: 2,
    refundableDamageDeposit: 15,
    personCapacity: 6,
    maxChildrenAllowed: null,
    maxInfantsAllowed: null,
    maxPetsAllowed: null,
    lat: 53.5403,
    lng: 8.58936,
    checkInTimeStart: 12,
    checkInTimeEnd: 21,
    checkOutTime: 11,
    cancellationPolicy: "strict",
    cancellationPolicyId: 4010,
    vrboCancellationPolicyId: 4011,
    airBnbCancellationPolicyId: 4012,
    marriottCancellationPolicyId: 4013,
    bookingCancellationPolicyId: 4013,
    squareMeters: 10,
    roomType: "entire_home",
    bathroomType: "shared",
    bedroomsNumber: 1,
    bedsNumber: 1,
    bedType: "real_bed",
    bathroomsNumber: 1,
    minNights: 1,
    maxNights: 1125,
    guestsIncluded: 3,
    cleaningFee: 40.32,
    priceForExtraPerson: 54.01,
    instantBookable: 0,
    instantBookableLeadTime: 1,
    allowSameDayBooking: 2,
    sameDayBookingLeadTime: 12,
    contactName: "John",
    contactSurName: "Doe",
    contactPhone1: "+49123456789",
    contactPhone2: "+49987654321",
    contactLanguage: "de",
    contactEmail: "contact@example.com",
    contactAddress: "Schulstraße 7",
    language: "en",
    currencyCode: "USD",
    timeZoneName: "Europe/Berlin",
    wifiUsername: "guest",
    wifiPassword: "welcome123",
    cleannessStatus: null,
    cleaningInstruction: null,
    cleannessStatusUpdatedOn: null,
    homeawayPropertyName: "Beautiful and cozy apartment close to city center",
    homeawayPropertyHeadline:
      "Beautiful and cozy apartment close to city center with a living room and bed room",
    homeawayPropertyDescription:
      "In a classic Bremerhaven house we rent out our apartment which has a living room, bed room and is close to all the restaurants and nightlife.",
    bookingcomPropertyName: "Beautiful and cozy apartment close to city center",
    bookingcomPropertyDescription:
      "In a classic Bremerhaven house we rent out our apartment which has a living room, bed room and is close to all the restaurants and nightlife.",
    invoicingContactName: "Jane",
    invoicingContactSurName: "Smith",
    invoicingContactPhone1: "+11122334456",
    invoicingContactPhone2: "+11122334456",
    invoicingContactLanguage: "en",
    invoicingContactEmail: "invoice@company.com",
    invoicingContactAddress: "221B Baker Street",
    invoicingContactCity: "London",
    invoicingContactZipcode: "110011",
    invoicingContactCountry: "UK",
    propertyLicenseNumber: null,
    propertyLicenseType: null,
    propertyLicenseIssueDate: null,
    propertyLicenseExpirationDate: null,
    partnersListingMarkup: null,
    airbnbOfficialListingMarkup: null,
    bookingEngineMarkup: null,
    homeawayApiMarkup: null,
    marriottListingMarkup: null,
    isRentalAgreementActive: true,
    listingAgreementText: "Rental agreement text for listing",
    bookingcomPropertyRegisteredInVcs: false,
    bookingcomPropertyHasVat: false,
    bookingcomPropertyDeclaresRevenue: false,
    airbnbListingUrl: "https://www.airbnb.com/rooms/1234567",
    vrboListingUrl: "https://www.vrbo.com/1234567",
    googleVrListingUrl:
      "http://www.google.com/travel/hotels/entity/1234567/overview",
    airbnbName: "",
    airbnbSummary: "",
    airbnbSpace: null,
    airbnbAccess: null,
    airbnbInteraction: null,
    airbnbNeighborhoodOverview: null,
    airbnbTransit: null,
    airbnbNotes: null,
    insuranceEligibilityStatus: false,
    googlePlaceId: "ChIJN1t_tDeuEmsRUsoyG83frY4",
    listingAmenities: [
      {
        id: 3449,
        amenityId: 2,
      },
      {
        id: 3444,
        amenityId: 3,
      },
    ],
    listingBedTypes: [
      {
        id: 1,
        bedTypeId: 2,
        quantity: 1,
      },
      {
        id: 2,
        bedTypeId: 33,
        quantity: 1,
      },
    ],
    listingImages: [
      {
        id: 877,
        caption: "Kitchen",
        url: "https://s3-us-west-2.amazonaws.com/hostaway-platform-dev/listing/10450-40160-fmR2QBJ-5jFbWDbHx-WcibQ5gXoSEq9V--FkCGtJ4jRE-591ab75c9816f",
        sortOrder: 1,
      },
      {
        id: 1027,
        caption: "Hall",
        url: "https://s3-us-west-2.amazonaws.com/hostaway-platform-dev/listing/10450-40160-QYseNxAOkr9LYYAwx4Vy-CQgo2gA0--lYu2Qqn8fpd3M-591ab82749ca1",
        sortOrder: 2,
      },
    ],
    customFieldValues: [
      {
        customFieldId: 167,
        value: "Custom field value one",
      },
      {
        customFieldId: 243,
        value: "Custom field value two",
      },
    ],
  },
  {
    id: 40161,
    propertyTypeId: 2,
    name: "Luxury Villa with Ocean View",
    externalListingName: "Luxury Villa with Ocean View",
    internalListingName: "Property #2",
    description:
      "Experience ultimate luxury in this stunning oceanfront villa. Wake up to breathtaking views of the Pacific Ocean and enjoy world-class amenities including a private pool, spa, and direct beach access.",
    houseRules: "No smoking, quiet hours after 10 PM",
    keyPickup: "Meet host at property",
    specialInstruction: "Gate code will be provided before arrival",
    doorSecurityCode: "vl85m",
    country: "USA",
    countryCode: "US",
    state: "California",
    city: "Malibu",
    street: "Pacific Coast Highway 123",
    address: "123 Pacific Coast Highway, Malibu, CA 90265, USA",
    publicAddress: "Malibu, CA 90265, USA",
    zipcode: "90265",
    price: 850.0,
    starRating: 5.0,
    averageReviewRating: 9.8,
    weeklyDiscount: 0.85,
    monthlyDiscount: 0.9,
    propertyRentTax: 15,
    guestPerPersonPerNightTax: 12,
    guestStayTax: 15,
    guestNightlyTax: 18,
    guestBathroomsNumber: 4,
    refundableDamageDeposit: 1000,
    personCapacity: 10,
    maxChildrenAllowed: 6,
    maxInfantsAllowed: 2,
    maxPetsAllowed: 2,
    lat: 34.0259,
    lng: -118.7798,
    checkInTimeStart: 15,
    checkInTimeEnd: 20,
    checkOutTime: 11,
    cancellationPolicy: "moderate",
    cancellationPolicyId: 4020,
    vrboCancellationPolicyId: 4021,
    airBnbCancellationPolicyId: 4022,
    marriottCancellationPolicyId: 4023,
    bookingCancellationPolicyId: 4023,
    squareMeters: 350,
    roomType: "entire_home",
    bathroomType: "private",
    bedroomsNumber: 5,
    bedsNumber: 6,
    bedType: "real_bed",
    bathroomsNumber: 4,
    minNights: 3,
    maxNights: 365,
    guestsIncluded: 8,
    cleaningFee: 250.0,
    priceForExtraPerson: 100.0,
    instantBookable: 1,
    instantBookableLeadTime: 2,
    allowSameDayBooking: 0,
    sameDayBookingLeadTime: 0,
    contactName: "Sarah",
    contactSurName: "Johnson",
    contactPhone1: "+13105551234",
    contactPhone2: "+13105555678",
    contactLanguage: "en",
    contactEmail: "sarah@luxuryvilla.com",
    contactAddress: "123 Pacific Coast Highway",
    language: "en",
    currencyCode: "USD",
    timeZoneName: "America/Los_Angeles",
    wifiUsername: "villa_guest",
    wifiPassword: "ocean2024",
    cleannessStatus: "clean",
    cleaningInstruction: "Full deep clean required between guests",
    cleannessStatusUpdatedOn: "2024-10-20T10:00:00Z",
    homeawayPropertyName: "Luxury Villa with Ocean View",
    homeawayPropertyHeadline:
      "Stunning 5BR Oceanfront Villa with Private Pool and Spa",
    homeawayPropertyDescription:
      "Experience ultimate luxury in this stunning oceanfront villa. Wake up to breathtaking views of the Pacific Ocean and enjoy world-class amenities including a private pool, spa, and direct beach access.",
    bookingcomPropertyName: "Luxury Villa with Ocean View",
    bookingcomPropertyDescription:
      "Experience ultimate luxury in this stunning oceanfront villa. Wake up to breathtaking views of the Pacific Ocean and enjoy world-class amenities including a private pool, spa, and direct beach access.",
    invoicingContactName: "Sarah",
    invoicingContactSurName: "Johnson",
    invoicingContactPhone1: "+13105551234",
    invoicingContactPhone2: "+13105555678",
    invoicingContactLanguage: "en",
    invoicingContactEmail: "billing@luxuryvilla.com",
    invoicingContactAddress: "123 Pacific Coast Highway",
    invoicingContactCity: "Malibu",
    invoicingContactZipcode: "90265",
    invoicingContactCountry: "USA",
    propertyLicenseNumber: "CA-12345",
    propertyLicenseType: "Short-term rental",
    propertyLicenseIssueDate: "2023-01-15",
    propertyLicenseExpirationDate: "2025-01-15",
    partnersListingMarkup: 10,
    airbnbOfficialListingMarkup: 15,
    bookingEngineMarkup: 12,
    homeawayApiMarkup: 14,
    marriottListingMarkup: 18,
    isRentalAgreementActive: true,
    listingAgreementText: "Standard rental agreement for luxury properties",
    bookingcomPropertyRegisteredInVcs: true,
    bookingcomPropertyHasVat: true,
    bookingcomPropertyDeclaresRevenue: true,
    airbnbListingUrl: "https://www.airbnb.com/rooms/2345678",
    vrboListingUrl: "https://www.vrbo.com/2345678",
    googleVrListingUrl:
      "http://www.google.com/travel/hotels/entity/2345678/overview",
    airbnbName: "Luxury Malibu Oceanfront Villa",
    airbnbSummary: "5BR villa with private pool and beach access",
    airbnbSpace: "Spacious 3500 sq ft villa with modern amenities",
    airbnbAccess: "Private entrance, parking for 4 cars",
    airbnbInteraction: "Self check-in, host available via phone",
    airbnbNeighborhoodOverview:
      "Exclusive Malibu neighborhood with beach access",
    airbnbTransit: "Car recommended, 30 min to LAX",
    airbnbNotes: "Perfect for families and special occasions",
    insuranceEligibilityStatus: true,
    googlePlaceId: "ChIJd8BlQ2BZwokRAFQEcDlJRAI",
    listingAmenities: [
      {
        id: 5001,
        amenityId: 1,
      },
      {
        id: 5002,
        amenityId: 5,
      },
      {
        id: 5003,
        amenityId: 8,
      },
    ],
    listingBedTypes: [
      {
        id: 101,
        bedTypeId: 1,
        quantity: 4,
      },
      {
        id: 102,
        bedTypeId: 3,
        quantity: 2,
      },
    ],
    listingImages: [
      {
        id: 1001,
        caption: "Ocean View from Master Bedroom",
        url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
        sortOrder: 1,
      },
      {
        id: 1002,
        caption: "Private Pool with Infinity Edge",
        url: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf",
        sortOrder: 2,
      },
      {
        id: 1003,
        caption: "Spacious Living Room",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
        sortOrder: 3,
      },
    ],
    customFieldValues: [
      {
        customFieldId: 300,
        value: "Beachfront property",
      },
      {
        customFieldId: 301,
        value: "Luxury tier",
      },
    ],
  },
];
