export type IListingAmenity = {
  id: number;
  amenityId: number;
};

export type IListingBedType = {
  id: number;
  bedTypeId: number;
  quantity: number;
};

export type IListingImage = {
  id: number;
  caption: string;
  url: string;
  sortOrder: number;
};

export type ICustomFieldValue = {
  customFieldId: number;
  value: string;
};

export type IListing = {
  id: number;
  propertyTypeId: number;
  name: string;
  externalListingName: string;
  internalListingName: string;
  description: string;
  houseRules: string;
  keyPickup: string;
  specialInstruction: string;
  doorSecurityCode: string;
  country: string;
  countryCode: string;
  state: string;
  city: string;
  street: string;
  address: string;
  publicAddress: string;
  zipcode: string;
  price: number;
  starRating: number;
  averageReviewRating: number;
  weeklyDiscount: number;
  monthlyDiscount: number;
  propertyRentTax: number;
  guestPerPersonPerNightTax: number;
  guestStayTax: number;
  guestNightlyTax: number;
  guestBathroomsNumber: number;
  refundableDamageDeposit: number;
  personCapacity: number;
  maxChildrenAllowed: number | null;
  maxInfantsAllowed: number | null;
  maxPetsAllowed: number | null;
  lat: number;
  lng: number;
  checkInTimeStart: number;
  checkInTimeEnd: number;
  checkOutTime: number;
  cancellationPolicy: string;
  cancellationPolicyId: number;
  vrboCancellationPolicyId: number;
  airBnbCancellationPolicyId: number;
  marriottCancellationPolicyId: number;
  bookingCancellationPolicyId: number;
  squareMeters: number;
  roomType: string;
  bathroomType: string;
  bedroomsNumber: number;
  bedsNumber: number;
  bedType: string;
  bathroomsNumber: number;
  minNights: number;
  maxNights: number;
  guestsIncluded: number;
  cleaningFee: number;
  priceForExtraPerson: number;
  instantBookable: number;
  instantBookableLeadTime: number;
  allowSameDayBooking: number;
  sameDayBookingLeadTime: number;
  contactName: string;
  contactSurName: string;
  contactPhone1: string;
  contactPhone2: string;
  contactLanguage: string;
  contactEmail: string;
  contactAddress: string;
  language: string;
  currencyCode: string;
  timeZoneName: string;
  wifiUsername: string;
  wifiPassword: string;
  cleannessStatus: string | null;
  cleaningInstruction: string | null;
  cleannessStatusUpdatedOn: string | null;
  homeawayPropertyName: string;
  homeawayPropertyHeadline: string;
  homeawayPropertyDescription: string;
  bookingcomPropertyName: string;
  bookingcomPropertyDescription: string;
  invoicingContactName: string;
  invoicingContactSurName: string;
  invoicingContactPhone1: string;
  invoicingContactPhone2: string;
  invoicingContactLanguage: string;
  invoicingContactEmail: string;
  invoicingContactAddress: string;
  invoicingContactCity: string;
  invoicingContactZipcode: string;
  invoicingContactCountry: string;
  propertyLicenseNumber: string | null;
  propertyLicenseType: string | null;
  propertyLicenseIssueDate: string | null;
  propertyLicenseExpirationDate: string | null;
  partnersListingMarkup: number | null;
  airbnbOfficialListingMarkup: number | null;
  bookingEngineMarkup: number | null;
  homeawayApiMarkup: number | null;
  marriottListingMarkup: number | null;
  isRentalAgreementActive: boolean;
  listingAgreementText: string;
  bookingcomPropertyRegisteredInVcs: boolean;
  bookingcomPropertyHasVat: boolean;
  bookingcomPropertyDeclaresRevenue: boolean;
  airbnbListingUrl: string;
  vrboListingUrl: string;
  googleVrListingUrl: string;
  airbnbName: string;
  airbnbSummary: string;
  airbnbSpace: string | null;
  airbnbAccess: string | null;
  airbnbInteraction: string | null;
  airbnbNeighborhoodOverview: string | null;
  airbnbTransit: string | null;
  airbnbNotes: string | null;
  insuranceEligibilityStatus: boolean;
  googlePlaceId?: string;
  listingAmenities: IListingAmenity[];
  listingBedTypes: IListingBedType[];
  listingImages: IListingImage[];
  customFieldValues: ICustomFieldValue[];
};

export type IUseListingsReturnTypes = {
  isLoading: boolean;
  isError: boolean;
  error: Error | null;
  data: IListing | null;
};

export type IFetchListingResponse = {
  status: "success" | "fail";
  result: IListing;
};

export type IApiErrorResponse = {
  status: "fail";
  message: string;
};
